Repository ipfs/boxo, pull requests merged in 2024-11, with the labels that each got.

#712 chore: update deps
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: skip/changelog

#711 fix(bitswap): log unexpected blocks to debug level
  CHANGELOG.md
  bitswap/client/internal/providerquerymanager/providerquerymanager.go
Labels: skip/changelog

#713 Release v0.24.3
  CHANGELOG.md
  bitswap/client/internal/providerquerymanager/providerquerymanager.go
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  version.json
Labels: release

#723 fix(bitswap/server): pass context to server engine to register metrics
  bitswap/server/internal/decision/engine.go
  bitswap/server/internal/decision/engine_test.go
  bitswap/server/server.go
Labels: skip/changelog

#721 fix(bitswap/client/providerquerymanager): use non-timed out context for tracing
  bitswap/client/internal/providerquerymanager/providerquerymanager.go
Labels: skip/changelog

#725 fix(bitswap/client/providerquerymanager): don't end trace span until …
  bitswap/client/internal/providerquerymanager/providerquerymanager.go
Labels: skip/changelog

#691 fix(bitswap/client/msgq): prevent duplicate requests
  CHANGELOG.md
  bitswap/client/internal/messagequeue/messagequeue.go
  bitswap/client/wantlist/wantlist.go
  bitswap/client/wantlist/wantlist_test.go
Labels: need/maintainers-input

#726 Tests can signal immediate rebroadcast
  bitswap/client/internal/messagequeue/messagequeue.go
  bitswap/client/internal/messagequeue/messagequeue_test.go
Labels: skip/changelog

#728 chore: minor Improvements to providerquerymanager
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  routing/providerquerymanager/providerquerymanager.go
  routing/providerquerymanager/providerquerymanager_test.go
Labels: skip/changelog

#729 Add debug logging for deduplicated queries
  routing/providerquerymanager/providerquerymanager.go
Labels: skip/changelog

#732 [skip changelog] bitswap/client: fix wiring when passing custom providerFinder
  bitswap/client/bitswap_with_sessions_test.go
  bitswap/client/client.go
Labels: skip/changelog
