Repository ipfs/boxo, pull requests merged in 2024-12, with the labels that each got.

#735 misc comments and spelling
  examples/README.md
  pinning/remote/client/openapi/README.md
  routing/providerquerymanager/providerquerymanager.go
Labels: skip/changelog

#736 chore: minor examples cleanup
  examples/bitswap-transfer/README.md
  examples/routing/delegated-routing-client/main.go
  examples/routing/delegated-routing-client/main_test.go
Labels: skip/changelog

#452 feat(session): do not record erroneous session want sends
  CHANGELOG.md
  bitswap/client/internal/peermanager/peermanager.go
  bitswap/client/internal/session/session.go
  bitswap/client/internal/session/session_test.go
  bitswap/client/internal/session/sessionwantsender.go
  bitswap/client/internal/session/sessionwantsender_test.go
  bitswap/client/internal/sessionmanager/sessionmanager_test.go
Labels: need/maintainers-input, need/triage

#740 Reenable flaky bitswap tests
  bitswap/client/internal/session/session_test.go
Labels: skip/changelog

#734 chore: no lifecycle context to shutdown ProviderQueryManager
  CHANGELOG.md
  bitswap/client/bitswap_with_sessions_test.go
  bitswap/client/client.go
  routing/providerquerymanager/providerquerymanager.go
  routing/providerquerymanager/providerquerymanager_test.go
Labels: skip/changelog

#742 Use deque instead of slice for queues
  bitswap/client/internal/messagequeue/donthavetimeoutmgr.go
  bitswap/client/internal/session/cidqueue.go
  bitswap/network/connecteventmanager.go
  bitswap/network/connecteventmanager_test.go
  bitswap/network/ipfs_impl.go
  bitswap/testnet/virtual.go
  ipld/merkledag/merkledag.go
  ipld/merkledag/traverse/traverse.go
  ipld/unixfs/hamt/hamt.go
Labels: skip/changelog

#754 improve mfs republisher
  mfs/repub.go
  mfs/repub_test.go
  mfs/root.go
Labels: skip/changelog

#755 [bitswap/peermanager] take read-lock for read-only operation
  bitswap/client/internal/peermanager/peermanager.go
  bitswap/client/internal/session/sessionwantsender.go
Labels: skip/changelog

#761 Remove unnecessary CID copying in SessionInterestManager
  bitswap/client/internal/sessioninterestmanager/sessioninterestmanager.go
Labels: skip/changelog

#757 Remove peer's count of first responses when peer becomes unavailable
  bitswap/client/internal/session/peerresponsetracker.go
  bitswap/client/internal/session/sessionwantsender.go
Labels: skip/changelog

#758 Do not reset the broadcast timer if there are no wants
  bitswap/client/internal/session/session.go
Labels: skip/changelog

#756 Fix leak due to cid queue never getting cleaned up
  bitswap/client/internal/blockpresencemanager/blockpresencemanager.go
  bitswap/client/internal/session/cidqueue.go
  bitswap/client/internal/session/sessionwants.go
Labels: skip/changelog

#768 Minor spelling and wording changes
  CHANGELOG.md
  bitswap/server/internal/decision/scoreledger.go
  mfs/dir.go
Labels: skip/changelog

#770 Release v0.26.0
  CHANGELOG.md
  version.json
Labels: release

#777 trivial spelling changes in comments
  bitswap/README.md
  bitswap/client/internal/messagequeue/messagequeue.go
  bitswap/server/internal/decision/engine.go
Labels: skip/changelog

#778 fix spelling in comments
  namesys/interface.go
  pinning/pinner/dspinner/pin_test.go
  routing/http/filters/filters.go
  routing/http/internal/goroutines.go
Labels: skip/changelog
