Repository ipfs/boxo, pull requests merged in 2024-10, with the labels that each got.

#678 feat: add protocol and address filtering to delegated routing api
  CHANGELOG.md
  routing/http/client/client.go
  routing/http/client/client_test.go
  routing/http/filters/filters.go
  routing/http/filters/filters_test.go
  routing/http/server/server.go
  routing/http/server/server_test.go
Labels: P1

#681 Update to latest go-libp2p
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: skip/changelog

#684 chore: update go-multiaddr-dns
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: skip/changelog

#683 Release v0.24.0
  CHANGELOG.md
  bitswap/internal/defaults/defaults.go
  bitswap/options.go
  bitswap/server/internal/decision/blockstoremanager.go
  bitswap/server/internal/decision/blockstoremanager_test.go
  bitswap/server/internal/decision/engine.go
  bitswap/server/internal/decision/engine_test.go
  bitswap/server/server.go
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  ipld/unixfs/hamt/hamt.go
  ipld/unixfs/hamt/hamt_test.go
  routing/http/client/client.go
  routing/http/client/client_test.go
  routing/http/filters/filters.go
  routing/http/filters/filters_test.go
  routing/http/server/server.go
  routing/http/server/server_test.go
  routing/http/types/iter/filter.go
  routing/http/types/iter/filter_test.go
  routing/http/types/record_peer.go
  version.json
Labels: release, skip/changelog

#686 chore: go-libp2p v0.36.5
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: skip/changelog

#687 refactor: reuse timers instead of time.After in loops
  bitswap/network/ipfs_impl.go
  bootstrap/bootstrap.go
  mfs/repub.go
Labels: skip/changelog

#676 refactor: bitswap client does not need ProviderQueryManager
  bitswap/client/client.go
Labels: skip/changelog

#690 fix(bitswap/session): cleanup live wants on cancel
  CHANGELOG.md
  bitswap/client/internal/session/sessionwants.go
Labels: P0

#693 chore: update dependencies
  .github/workflows/gateway-sharness.yml
  examples/go.mod
  examples/go.sum
  gateway/blockstore.go
  go.mod
  go.sum
Labels: skip/changelog

#544 provider: add MaxBatchSize limit
  provider/reprovider.go
Labels: skip/changelog

#697 Release v0.24.1
  CHANGELOG.md
  version.json
Labels: release

#702 bitswap(session): fix slice prealloc
  CHANGELOG.md
  bitswap/client/internal/session/sessionwants.go
Labels: P0

#707 Release v0.24.2
  CHANGELOG.md
  bitswap/client/internal/session/sessionwants.go
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  ipns/pb/record.pb.go
  version.json
Labels: release
