Repository ipfs/boxo, pull requests merged in 2025-03, with the labels that each got.

#866 update dependencies
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: skip/changelog

#867 Do not use multiple multi-error packages, pick one
  .github/workflows/gateway-sharness.yml
  examples/go.mod
  examples/go.sum
  gateway/backend_car.go
  go.mod
  go.sum
Labels: skip/changelog

#869 Release v0.29.0
  .github/workflows/gateway-sharness.yml
  CHANGELOG.md
  version.json
Labels: release

#870 provider: add a buffered KeyChanFunc.
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  provider/provider.go
  provider/provider_test.go
Labels: skip/changelog

#882 Nonfunctional
  examples/gateway/car-file/README.md
  files/filewriter_test.go
  files/filewriter_unix_test.go
  files/filewriter_windows_test.go
  files/filter_test.go
  files/serialfile_test.go
  filestore/filestore_test.go
  keystore/keystore.go
  keystore/keystore_test.go
  tar/extractor_test.go
Labels: skip/changelog, kind/nonfunctional

#878 bitswap/httpnet: do not follow redirects
  bitswap/network/httpnet/httpnet.go
  bitswap/network/httpnet/msg_sender.go
Labels: skip/changelog

#885 Release v0.29.1
  CHANGELOG.md
  version.json
Labels: release

#877 bitswap/httpnet: Add WithDenylist option
  bitswap/network/http_multiaddr.go
  bitswap/network/httpnet/httpnet.go
  bitswap/network/httpnet/httpnet_test.go
  bitswap/network/httpnet/msg_sender.go
  bitswap/network/httpnet/pinger.go
  bitswap/network/router.go
Labels: skip/changelog

#892 Update RELEASE.md
  RELEASE.md
Labels: skip/changelog
