Repository ipfs/boxo, pull requests merged in 2025-06, with the labels that each got.

#939 bitswap/httpnet: expose the errors on connect when connection impossible
  bitswap/network/httpnet/httpnet.go
  bitswap/network/httpnet/httpnet_test.go
Labels: skip/changelog

#940 chore(provider): meaningful info level log
  CHANGELOG.md
  provider/internal/queue/queue.go
  provider/provider.go
  provider/reprovider.go
Labels: skip/changelog

#952 Release v0.32.0
  CHANGELOG.md
  version.json
Labels: release

#953 docs: reprovider metrics name in changelog
  CHANGELOG.md
Labels: skip/changelog

#958 bitswap/httpnet: adjust error logging
  bitswap/network/httpnet/httpnet.go
  bitswap/network/httpnet/msg_sender.go
Labels: skip/changelog

#941 refactor: use the built-in max/min to simplify the code [skip changelog]
  bitswap/benchmarks_test.go
  gateway/backend_blocks.go
  ipld/merkledag/coding.go
Labels: need/author-input, kind/generated

#957 bitswap/httpnet: limit metric cardinality
  CHANGELOG.md
  bitswap/network/httpnet/httpnet.go
  bitswap/network/httpnet/metrics.go
Labels: skip/changelog
