Repository ipfs/boxo, pull requests merged in 2025-04, with the labels that each got.

#899 feat(gateway): add cid copy button to directory listings
  CHANGELOG.md
  gateway/assets/directory.html
  gateway/assets/icons.css
  gateway/assets/style.css
Labels: need/maintainers-input

#903 gateway: validate against subdomains with IP addresses
  CHANGELOG.md
  gateway/hostname.go
  gateway/hostname_test.go
Labels: need/author-input

#913 Update dependencies
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: skip/changelog

#915 Release v0.30.0
  CHANGELOG.md
  version.json
Labels: release
